# Site settings
email: cwhelman@gmail.com
baseurl: "/mynameiscash"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-70791392-1

# SEO settings
title: Cash Helman
description: That's my name
url: "http://mynameiscash.github.io"
twitter_username: mynamescash
default_img: 

# Profile settings
name: Cash Helman
profile_img: https://unsplash.it/500/300?image=817
profile: I studied Natural Resources Management in college, but somehow ended up being an English teacher in Japan. When I am not working, I write songs, cook, and exercise frequently.
social:
  github: https://github.com/mynameiscash
  twitter: https://twitter.com/mynamescash
  linkedin: https://www.linkedin.com/in/cash-helman-151a9574


# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
