# Site settings
email: cwhelman@gmail.com
baseurl: "/mynameiscash"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Cash Helman
description: That's my name
url: "http://mynameiscash.github.io"
twitter_username: mynamescash
default_img: 

# Profile settings
name: Cash Helman
profile_img: 
profile: My name is Cash. Yes, you read that correctly. How did I get that name, you may be wondering? Simply put, My parents wanted me to be rich. Unfortunately for them (and me), it hasn’t worked out yet. But I am optimistic! I won’t bore you with the little details of my life, but all you need to know is that I live in Buzen, Japan, make music, and eat copious amounts of ice cream. To offset my huge calorie intake, I try to spend as much of my free time being outdoors.
social:
  github: mynameiscash

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
